### ISSUE TITLE
write_map error

### ISSUE THREAD

**Issue by DanBThomas** [JulienPeloton/LaFabrique#1]
Hey

I downloaded this yesterday.
As far as I can tell all the dependencies have installed correctly, but I'm getting this error:

Traceback (most recent call last):
  File "generate_dataset.py", line 98, in <module>
    noise.generate_noise_sims(args.setup_instrument, comm, environment)
  File "/home/dthomas/simons/fabrique_clean/LaFabrique/LaFabrique/noise.py", line 89, in generate_noise_sims
    covariance.generate_covariances(m1_output, instrument)
  File "/home/dthomas/simons/fabrique_clean/LaFabrique/LaFabrique/covariance.py", line 46, in generate_covariances
    ('sigma_p [uK.arcmin]', m1.sigma_p)])
  File "/home/dthomas/simons/fabrique_clean/LaFabrique/LaFabrique/util_CMB.py", line 150, in wrapper
    res = func(*args, **kwargs)
  File "/home/dthomas/simons/fabrique_clean/LaFabrique/LaFabrique/util_CMB.py", line 237, in write_map
    extra_header=extra_header)
TypeError: write_map() got an unexpected keyword argument 'column_units'

Any ideas?
Thanks
Dan

**Comment by JulienPeloton** [comment]
Hi Dan,

Thanks for trying the code!
Your error is likely due to a different version of healpy than mine.
I'm using an old version (1.9.1). What is yours?
Julien

**Comment by DanBThomas** [comment]
I have healpy-1-10-3 installed.
I think that is healpix 3.30.0, but I couldn't seem to find a definitive answer in the documentation.

**Comment by DanBThomas** [comment]
No worries, updating healpy solved the problem.

**Comment by JulienPeloton** [comment]
Great! In any case, I have warning about this (I guess it would be easier to pack everything in the extra_header) so I may update that in the future.
Julien
